import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for ContentAI.',
  alternates: { canonical: 'https://contentai.ca/terms' },
  openGraph: {
    type: 'website',
    url: 'https://contentai.ca/terms',
    title: 'Terms of Service | ContentAI',
    description: 'Terms of Service for ContentAI.',
  },
}

const LAST_UPDATED = 'June 1, 2025'
const EMAIL = 'support@contentai.ca'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="text-[#0D7377] hover:underline text-sm mb-8 inline-block">← Back to home</Link>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing or using ContentAI (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed">
              ContentAI is an AI-powered content generation platform that helps users create
              marketing content in English, French, and Arabic. We use Anthropic&apos;s Claude AI models
              to generate text content based on user-provided prompts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Account Registration</h2>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>One account per person or entity; creating multiple accounts to circumvent limits is prohibited.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Acceptable Use</h2>
            <p className="text-gray-600 leading-relaxed mb-2">You agree not to use ContentAI to generate:</p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Content that is illegal, harmful, threatening, abusive, or defamatory.</li>
              <li>Spam, misinformation, or deceptive content.</li>
              <li>Content that infringes on intellectual property rights.</li>
              <li>Content that violates any applicable laws or regulations.</li>
            </ul>
            <p className="text-gray-600 mt-3">
              We reserve the right to suspend accounts that violate these guidelines without notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              You retain ownership of the prompts you submit. For content generated by ContentAI,
              you are granted a non-exclusive license to use, reproduce, and distribute such content.
              ContentAI retains no rights to your generated content. The ContentAI platform, brand,
              and underlying technology remain our exclusive property.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Subscriptions and Payments</h2>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Paid plans are billed monthly or annually in advance.</li>
              <li>All prices are in CAD and exclude applicable taxes.</li>
              <li>Subscriptions auto-renew unless cancelled before the renewal date.</li>
              <li>No refunds for partial months, except where required by law.</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Generation Limits</h2>
            <p className="text-gray-600 leading-relaxed">
              Each plan includes a monthly generation quota. Unused generations do not roll over.
              We may impose API rate limits (10 requests per minute per user) to ensure fair service
              for all users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Disclaimer of Warranties</h2>
            <p className="text-gray-600 leading-relaxed">
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee
              that AI-generated content is accurate, complete, or suitable for any particular purpose.
              You are solely responsible for reviewing and verifying generated content before use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              To the maximum extent permitted by law, ContentAI shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of the Service.
              Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Termination</h2>
            <p className="text-gray-600 leading-relaxed">
              You may cancel your account at any time from the billing settings. We may terminate
              or suspend your account for violations of these Terms without prior notice.
              Upon termination, your data will be retained for 30 days before deletion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Governing Law</h2>
            <p className="text-gray-600 leading-relaxed">
              These Terms are governed by the laws of the Province of Quebec, Canada. Any disputes
              shall be resolved in the courts of Quebec.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We may update these Terms from time to time. Continued use of the Service after changes
              constitutes acceptance of the new Terms. Material changes will be communicated by email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">13. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              For legal inquiries, contact us at{' '}
              <a href={`mailto:${EMAIL}`} className="text-[#0D7377] hover:underline">{EMAIL}</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
